version: "3"

#Docker Networks
networks:
  backend:
    driver: bridge

services:
  app:
    build: .
    volumes:
      - ./:/app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./doc_site.conf:/etc/nginx/conf.d/doc_site.conf
    links:
      - app
    networks:
      - backend

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: doc_site
      MYSQL_USER: root
    ports:
      - '3306:3306'
    networks:
      - backend
